name: metamask
description: sing in with metamask, connect to ethereum network
version: 0.0.2
homepage: https://github.com/Abdusin/flutter_metamask_login
repository: https://github.com/Abdusin/flutter_metamask_login

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: